site_name: Telcoin Network
site_url: https://leopashov.github.io/tn-docs/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: indigo
      accent: light blue
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/favicon.png

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - redirects
extra_css:
  - assets/cards.css
