name: Deploy GitBook to Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]   # only publish from your fork's main

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

concurrency:
  group: pages-deploy
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    # never run on the Telcoin-Association repo by accident
    if: github.repository == 'leopashov/tn-docs'

    runs-on: ubuntu-latest
    container: node:10.24.1
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Install GitBook CLI
        run: npm install -g gitbook-cli@2.3.2

      - name: Pin GitBook runtime
        run: gitbook fetch 3.2.3

      - name: Install plugins (with simple retry)
        run: |
          gitbook install || (npm cache clean -f && gitbook install)

      - name: Clean output dir
        run: rm -rf _book

      - name: Build site to ./_book (verbose)
        run: gitbook build "$(pwd)" "$(pwd)/_book" --log=debug --debug

      - name: Add 404.html fallback
        run: |
          if [ -f "_book/index.html" ] && [ ! -f "_book/404.html" ]; then
            cp _book/index.html _book/404.html
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_book

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v3

