name: Build & Deploy MkDocs

on:
  push:
    branches: [ main, docs/mkdocs-material ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'leopashov/tn-docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install MkDocs + Material
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material pymdown-extensions mkdocs-redirects
      - name: Build MkDocs
        run: mkdocs build --strict
      - name: Upload site artifact (for preview)
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-site
          path: site

  deploy:
    needs: build
    if: github.repository == 'leopashov/tn-docs' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: mkdocs-site
          path: site
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - id: deployment
        uses: actions/deploy-pages@v4